version: '3'

volumes:
  wp:
    driver: local
    driver_opts:
      o: bind
      type: none
<<<<<<< HEAD
      device: /home/mhaksal/data/wp
=======
      device: /Users/mhaksal/data/wp
>>>>>>> 2a8568048bed8f8ed809d1e5ecb3250b06a626f0
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
<<<<<<< HEAD
      device: /home/mhaksal/data/db
=======
      device: /Users/mhaksal/data/db
>>>>>>> 2a8568048bed8f8ed809d1e5ecb3250b06a626f0

networks:
  wp:
    driver: bridge
    
services:
  mariadb:
    container_name: mariadb
    networks:
      - wp
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
<<<<<<< HEAD
        DB_NAME: $MYSQL_DB
        DB_USER: $MYSQL_USER
        DB_PASSWORD: $MYSQL_PASSWORD
        DB_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
=======
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_DB: $MYSQL_DB
>>>>>>> 2a8568048bed8f8ed809d1e5ecb3250b06a626f0
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - /home/mhaksal/data/db:/home/data
    restart: always
    tty: true
  nginx:
<<<<<<< HEAD
    container_name: nginx
=======
>>>>>>> 2a8568048bed8f8ed809d1e5ecb3250b06a626f0
    depends_on:
      - wordpress
    networks:
      - wp
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "443:443"
    restart: always
    volumes:
<<<<<<< HEAD
      - wp:/var/www/html
    tty: true
  wordpress:
    container_name: wordpress
=======
      - /home/mhaksal/data/nginx:/home/data
    tty: true
  wordpress:
>>>>>>> 2a8568048bed8f8ed809d1e5ecb3250b06a626f0
    depends_on:
      - mariadb
    networks:
      - wp
    build:
      context: ./wp
      dockerfile: Dockerfile
      args:
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_HOST: $MYSQL_HOST
        MYSQL_DB: $MYSQL_DB
    ports:
      - "9000:9000"
    volumes:
<<<<<<< HEAD
      - wp:/var/www/html
=======
      - /home/mhaksal/data/wp:/home/data
>>>>>>> 2a8568048bed8f8ed809d1e5ecb3250b06a626f0
    restart: always
    tty: true