version: '3'

volumes:
  wp:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/mhaksal/data/wp
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/mhaksal/data/db

networks:
  wp:
    driver: bridge
    
services:
  mariadb:
    container_name: mariadb
    networks:
      - wp
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_DB: $MYSQL_DB
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - /home/mhaksal/data/db:/home/data
    restart: always
    tty: true
  nginx:
    depends_on:
      - wordpress
    networks:
      - wp
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "443:443"
    restart: always
    volumes:
      - /home/mhaksal/data/nginx:/home/data
    tty: true
  wordpress:
    depends_on:
      - mariadb
    networks:
      - wp
    build:
      context: ./wp
      dockerfile: Dockerfile
      args:
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_HOST: $MYSQL_HOST
        MYSQL_DB: $MYSQL_DB
    ports:
      - "9000:9000"
    volumes:
      - /home/mhaksal/data/wp:/home/data
    restart: always
    tty: true