version: '3'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: always
    tty: true
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/html:/home/mhaksal/data/nginx/html
    tty: true